// <auto-generated />
using System;
using ApexRacers.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ApexRacers.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261004012741_DriverLifecycleAdmissionSpine")]
    partial class DriverLifecycleAdmissionSpine
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("iracing")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ApexRacers.Core.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("AssetFolder")
                        .HasColumnType("text");

                    b.Property<string>("CarMake")
                        .HasColumnType("text");

                    b.Property<string>("CarModel")
                        .HasColumnType("text");

                    b.Property<string>("CarTypesJson")
                        .HasColumnType("text");

                    b.Property<int?>("CarWeight")
                        .HasColumnType("integer");

                    b.Property<string>("CategoriesJson")
                        .HasColumnType("text");

                    b.Property<bool?>("FreeWithSubscription")
                        .HasColumnType("boolean");

                    b.Property<int?>("Hp")
                        .HasColumnType("integer");

                    b.Property<string>("LargeImageFile")
                        .HasColumnType("text");

                    b.Property<string>("LogoPath")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NameAbbreviated")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("PackageId")
                        .HasColumnType("integer");

                    b.Property<bool>("RainEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool?>("Retired")
                        .HasColumnType("boolean");

                    b.Property<string>("SmallImageFile")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Cars", "iracing");
                });

            modelBuilder.Entity("ApexRacers.Core.Models.CarClass", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("RelativeSpeed")
                        .HasColumnType("integer");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("CarClasses", "iracing");
                });

            modelBuilder.Entity("ApexRacers.Core.Models.CarClassCar", b =>
                {
                    b.Property<int>("CarClassId")
                        .HasColumnType("integer");

                    b.Property<int>("CarId")
                        .HasColumnType("integer");

                    b.HasKey("CarClassId", "CarId");

                    b.HasIndex("CarId");

                    b.ToTable("CarClassCars", "iracing");
                });

            modelBuilder.Entity("ApexRacers.Core.Models.CarPercentileResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CarId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("ComputedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("PercentileRank")
                        .HasColumnType("double precision");

                    b.Property<int>("Provenance")
                        .HasColumnType("integer");

                    b.Property<int>("SampleSize")
                        .HasColumnType("integer");

                    b.Property<int>("SeriesId")
                        .HasColumnType("integer");

                    b.Property<int>("TopSharePercent")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WeekId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("SeriesId");

                    b.HasIndex("UserId");

                    b.HasIndex("WeekId");

                    b.HasIndex("Provenance", "UserId", "CarId", "SeriesId", "WeekId")
                        .IsUnique();

                    b.ToTable("ScopedCarPercentileResults", "iracing");
                });

            modelBuilder.Entity("ApexRacers.Core.Models.DriverAuthorizationGrant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuthorizedDriverName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("BindingActive")
                        .HasColumnType("boolean");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("PersonalClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PersonalConsentVersion")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("ProofReceiptId")
                        .HasColumnType("uuid");

                    b.Property<bool>("ProofValid")
                        .HasColumnType("boolean");

                    b.Property<int>("Provenance")
                        .HasColumnType("integer");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("SharingClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SharingConsentVersion")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Provenance", "CustomerId")
                        .IsUnique()
                        .HasFilter("\"BindingActive\" = TRUE");

                    b.HasIndex("Provenance", "UserId")
                        .IsUnique()
                        .HasFilter("\"BindingActive\" = TRUE");

                    b.HasIndex("Provenance", "UserId", "CustomerId")
                        .IsUnique();

                    b.HasIndex("ProofReceiptId", "UserId", "CustomerId", "Provenance");

                    b.ToTable("DriverAuthorizationGrants", "iracing", t =>
                        {
                            t.HasCheckConstraint("CK_DriverGrant_ConsentProof", "\"ProofValid\" OR (\"PersonalConsentVersion\" IS NULL AND \"SharingConsentVersion\" IS NULL AND \"AuthorizedDriverName\" IS NULL)");

                            t.HasCheckConstraint("CK_DriverGrant_Provenance", "\"Provenance\" IN (1, 2)");

                            t.HasCheckConstraint("CK_DriverGrant_Revision", "\"Revision\" > 0");

                            t.HasCheckConstraint("CK_DriverGrant_SharingPersonal", "\"SharingConsentVersion\" IS NULL OR \"PersonalConsentVersion\" IS NOT NULL");
                        });
                });

            modelBuilder.Entity("ApexRacers.Core.Models.DriverCopyCleanup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DueAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GrantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("OriginalLossAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Purpose")
                        .HasColumnType("integer");

                    b.Property<long>("ThroughRevision")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("VerifiedRemovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GrantId");

                    b.HasIndex("OperationId", "Purpose")
                        .IsUnique();

                    b.HasIndex("VerifiedRemovedAt", "DueAt");

                    b.HasIndex("OperationId", "GrantId", "OriginalLossAt");

                    b.ToTable("DriverCopyCleanups", "iracing", t =>
                        {
                            t.HasCheckConstraint("CK_DriverCleanup_Deadline", "\"DueAt\" >= \"OriginalLossAt\"");

                            t.HasCheckConstraint("CK_DriverCleanup_Purpose", "\"Purpose\" IN (1, 2)");

                            t.HasCheckConstraint("CK_DriverCleanup_ThroughRevision", "\"ThroughRevision\" > 0");
                        });
                });

            modelBuilder.Entity("ApexRacers.Core.Models.DriverLifecycleOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("AppliedRevision")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GrantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("OriginalLossAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("PrimaryAppliedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GrantId", "CompletedAt");

                    b.ToTable("DriverLifecycleOperations", "iracing", t =>
                        {
                            t.HasCheckConstraint("CK_DriverOperation_Kind", "\"Kind\" IN (1, 2, 3, 4, 5)");

                            t.HasCheckConstraint("CK_DriverOperation_Revision", "\"AppliedRevision\" > 0");
                        });
                });

            modelBuilder.Entity("ApexRacers.Core.Models.DriverProofReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Authority")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<int>("Provenance")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("VerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("DriverProofReceipts", "iracing", t =>
                        {
                            t.HasCheckConstraint("CK_DriverProof_Provenance", "\"Provenance\" IN (1, 2)");
                        });
                });

            modelBuilder.Entity("ApexRacers.Core.Models.DriverPublicationAdmission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AdmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GrantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Incarnation")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("LeaseUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Purpose")
                        .HasColumnType("integer");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("TerminalAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Incarnation");

                    b.HasIndex("GrantId", "Purpose", "TerminalAt");

                    b.ToTable("DriverPublicationAdmissions", "iracing", t =>
                        {
                            t.HasCheckConstraint("CK_DriverAdmission_Purpose", "\"Purpose\" IN (1, 2)");

                            t.HasCheckConstraint("CK_DriverAdmission_Revision", "\"Revision\" > 0");
                        });
                });

            modelBuilder.Entity("ApexRacers.Core.Models.DriverTrackedCopy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GrantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasMaxLength(16384)
                        .HasColumnType("character varying(16384)");

                    b.Property<int>("Purpose")
                        .HasColumnType("integer");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("UnavailableAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GrantId", "Purpose", "UnavailableAt");

                    b.ToTable("DriverTrackedCopies", "iracing", t =>
                        {
                            t.HasCheckConstraint("CK_DriverCopy_Purpose", "\"Purpose\" IN (1, 2)");

                            t.HasCheckConstraint("CK_DriverCopy_Revision", "\"Revision\" > 0");
                        });
                });

            modelBuilder.Entity("ApexRacers.Core.Models.ExternalDataCache", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CacheKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Provenance")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Provenance", "CacheKey")
                        .IsUnique();

                    b.ToTable("MappedDataCaches", "iracing", t =>
                        {
                            t.HasCheckConstraint("CK_MappedDataCaches_KnownProvenance", "\"Provenance\" IN (1, 2)");
                        });
                });

            modelBuilder.Entity("ApexRacers.Core.Models.FeatureFlag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MinimumRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("FeatureFlags", "iracing");
                });

            modelBuilder.Entity("ApexRacers.Core.Models.KnownDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FailureCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("WindowStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId", "LastSeenAt");

                    b.ToTable("KnownDevices", "identity");
                });

            modelBuilder.Entity("ApexRacers.Core.Models.ProvenanceMigrationInventory", b =>
                {
                    b.Property<string>("StorageKind")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UnknownRows")
                        .HasColumnType("bigint");

                    b.HasKey("StorageKind");

                    b.ToTable("ProvenanceMigrationInventory", "iracing");
                });

            modelBuilder.Entity("ApexRacers.Core.Models.QuarantinedDataCache", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CacheKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CacheKey")
                        .IsUnique();

                    b.ToTable("QuarantinedDataCaches", "iracing");
                });

            modelBuilder.Entity("ApexRacers.Core.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", "identity");
                });

            modelBuilder.Entity("ApexRacers.Core.Models.Rival", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Provenance")
                        .HasColumnType("integer");

                    b.Property<long>("RivalCustId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("Provenance", "UserId", "RivalCustId")
                        .IsUnique();

                    b.ToTable("ScopedRivals", "iracing");
                });

            modelBuilder.Entity("ApexRacers.Core.Models.Season", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<int?>("Drops")
                        .HasColumnType("integer");

                    b.Property<bool?>("FixedSetup")
                        .HasColumnType("boolean");

                    b.Property<int?>("LicenseGroup")
                        .HasColumnType("integer");

                    b.Property<bool?>("Multiclass")
                        .HasColumnType("boolean");

                    b.Property<bool?>("Official")
                        .HasColumnType("boolean");

                    b.Property<int>("Quarter")
                        .HasColumnType("integer");

                    b.Property<int>("SeriesId")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SeriesId", "Year", "Quarter")
                        .IsUnique();

                    b.ToTable("Seasons", "iracing");
                });

            modelBuilder.Entity("ApexRacers.Core.Models.SeasonCar", b =>
                {
                    b.Property<int>("SeasonId")
                        .HasColumnType("integer");

                    b.Property<int>("CarId")
                        .HasColumnType("integer");

                    b.HasKey("SeasonId", "CarId");

                    b.HasIndex("CarId");

                    b.ToTable("SeasonCars", "iracing");
                });

            modelBuilder.Entity("ApexRacers.Core.Models.SeasonCarBop", b =>
                {
                    b.Property<int>("Provenance")
                        .HasColumnType("integer");

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer");

                    b.Property<int>("RaceWeekIndex")
                        .HasColumnType("integer");

                    b.Property<int>("CarId")
                        .HasColumnType("integer");

                    b.Property<int>("MaxDryTireSets")
                        .HasColumnType("integer");

                    b.Property<double>("MaxPctFuelFill")
                        .HasColumnType("double precision");

                    b.Property<double>("PowerAdjustPct")
                        .HasColumnType("double precision");

                    b.Property<double>("WeightPenaltyKg")
                        .HasColumnType("double precision");

                    b.HasKey("Provenance", "SeasonId", "RaceWeekIndex", "CarId");

                    b.HasIndex("SeasonId", "RaceWeekIndex");

                    b.ToTable("ScopedSeasonCarBops", "iracing");
                });

            modelBuilder.Entity("ApexRacers.Core.Models.SeasonCarClass", b =>
                {
                    b.Property<int>("SeasonId")
                        .HasColumnType("integer");

                    b.Property<int>("CarClassId")
                        .HasColumnType("integer");

                    b.HasKey("SeasonId", "CarClassId");

                    b.HasIndex("CarClassId");

                    b.ToTable("SeasonCarClasses", "iracing");
                });

            modelBuilder.Entity("ApexRacers.Core.Models.Series", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<int?>("LicenseGroup")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool?>("Official")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Series", "iracing");
                });

            modelBuilder.Entity("ApexRacers.Core.Models.SignInAccountFailure", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("FailureCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("LastFailureAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("NoticeSentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("WindowStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId");

                    b.HasIndex("LastFailureAt");

                    b.ToTable("SignInAccountFailures", "identity");
                });

            modelBuilder.Entity("ApexRacers.Core.Models.SignInAddressFailure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("FailureCount")
                        .HasColumnType("integer");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(56)
                        .HasColumnType("character varying(56)");

                    b.Property<DateTimeOffset>("LastFailureAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("WindowStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LastFailureAt");

                    b.HasIndex("UserId", "IpAddress")
                        .IsUnique();

                    b.ToTable("SignInAddressFailures", "identity");
                });

            modelBuilder.Entity("ApexRacers.Core.Models.Subsession", b =>
                {
                    b.Property<int>("Provenance")
                        .HasColumnType("integer");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int?>("AiEntryCount")
                        .HasColumnType("integer");

                    b.Property<int>("CornersPerLap")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("EventAverageLapSeconds")
                        .HasColumnType("double precision");

                    b.Property<double>("EventBestLapSeconds")
                        .HasColumnType("double precision");

                    b.Property<int>("EventLapsComplete")
                        .HasColumnType("integer");

                    b.Property<int>("EventStrengthOfField")
                        .HasColumnType("integer");

                    b.Property<int>("NumCautionLaps")
                        .HasColumnType("integer");

                    b.Property<int>("NumCautions")
                        .HasColumnType("integer");

                    b.Property<int>("NumLeadChanges")
                        .HasColumnType("integer");

                    b.Property<bool>("OfficialSession")
                        .HasColumnType("boolean");

                    b.Property<int?>("RaceSessionId")
                        .HasColumnType("integer");

                    b.Property<int>("RaceWeekIndex")
                        .HasColumnType("integer");

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer");

                    b.Property<int?>("SplitCount")
                        .HasColumnType("integer");

                    b.Property<int?>("SplitIndex")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("TeamEntryCount")
                        .HasColumnType("integer");

                    b.Property<int>("TrackId")
                        .HasColumnType("integer");

                    b.Property<string>("TrackStateJson")
                        .HasColumnType("text");

                    b.Property<string>("WeatherJson")
                        .HasColumnType("text");

                    b.Property<Guid?>("WeekId")
                        .HasColumnType("uuid");

                    b.HasKey("Provenance", "Id");

                    b.HasIndex("RaceSessionId");

                    b.HasIndex("TrackId");

                    b.HasIndex("WeekId");

                    b.HasIndex("SeasonId", "RaceWeekIndex");

                    b.ToTable("RaceEvidenceSubsessions", "iracing");
                });

            modelBuilder.Entity("ApexRacers.Core.Models.SubsessionResult", b =>
                {
                    b.Property<int>("Provenance")
                        .HasColumnType("integer");

                    b.Property<int>("SubsessionId")
                        .HasColumnType("integer");

                    b.Property<long>("CustId")
                        .HasColumnType("bigint");

                    b.Property<int>("AggregateChampPoints")
                        .HasColumnType("integer");

                    b.Property<double>("AverageLapSeconds")
                        .HasColumnType("double precision");

                    b.Property<double>("BestLapSeconds")
                        .HasColumnType("double precision");

                    b.Property<int>("CarClassId")
                        .HasColumnType("integer");

                    b.Property<int>("CarId")
                        .HasColumnType("integer");

                    b.Property<int>("ChampPoints")
                        .HasColumnType("integer");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<int>("Division")
                        .HasColumnType("integer");

                    b.Property<bool>("DropRace")
                        .HasColumnType("boolean");

                    b.Property<int>("FinishPosition")
                        .HasColumnType("integer");

                    b.Property<int>("FinishPositionInClass")
                        .HasColumnType("integer");

                    b.Property<int>("Incidents")
                        .HasColumnType("integer");

                    b.Property<double>("Interval")
                        .HasColumnType("double precision");

                    b.Property<int>("LapsComplete")
                        .HasColumnType("integer");

                    b.Property<int>("LapsLead")
                        .HasColumnType("integer");

                    b.Property<double>("NewCpi")
                        .HasColumnType("double precision");

                    b.Property<int>("NewIRating")
                        .HasColumnType("integer");

                    b.Property<int>("NewSubLevel")
                        .HasColumnType("integer");

                    b.Property<int>("NewTtRating")
                        .HasColumnType("integer");

                    b.Property<double>("OldCpi")
                        .HasColumnType("double precision");

                    b.Property<int>("OldIRating")
                        .HasColumnType("integer");

                    b.Property<int>("OldSubLevel")
                        .HasColumnType("integer");

                    b.Property<int>("OldTtRating")
                        .HasColumnType("integer");

                    b.Property<double>("QualLapSeconds")
                        .HasColumnType("double precision");

                    b.Property<string>("ReasonOut")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ReasonOutId")
                        .HasColumnType("integer");

                    b.Property<int>("StartingPosition")
                        .HasColumnType("integer");

                    b.Property<int>("StartingPositionInClass")
                        .HasColumnType("integer");

                    b.HasKey("Provenance", "SubsessionId", "CustId");

                    b.HasIndex("CarClassId");

                    b.HasIndex("CustId");

                    b.HasIndex("CarId", "SubsessionId");

                    b.ToTable("RaceEvidenceResults", "iracing");
                });

            modelBuilder.Entity("ApexRacers.Core.Models.Track", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AssetFolder")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("ConfigName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("CornersPerLap")
                        .HasColumnType("integer");

                    b.Property<bool>("HasSvgMap")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDirt")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOval")
                        .HasColumnType("boolean");

                    b.Property<string>("LargeImageFile")
                        .HasColumnType("text");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("NightLighting")
                        .HasColumnType("boolean");

                    b.Property<int?>("NumberPitstalls")
                        .HasColumnType("integer");

                    b.Property<int?>("PitRoadSpeedLimit")
                        .HasColumnType("integer");

                    b.Property<bool>("Retired")
                        .HasColumnType("boolean");

                    b.Property<string>("SmallImageFile")
                        .HasColumnType("text");

                    b.Property<string>("TimeZone")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double?>("TrackConfigLength")
                        .HasColumnType("double precision");

                    b.Property<string>("TrackMapUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tracks", "iracing");
                });

            modelBuilder.Entity("ApexRacers.Core.Models.UploadedLap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float>("AirTempCelsius")
                        .HasColumnType("real");

                    b.Property<int>("CarId")
                        .HasColumnType("integer");

                    b.Property<long?>("DriverCustId")
                        .HasColumnType("bigint");

                    b.Property<double>("LapTimeSeconds")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte>("SessionType")
                        .HasColumnType("smallint");

                    b.Property<int>("TrackId")
                        .HasColumnType("integer");

                    b.Property<float>("TrackTempCelsius")
                        .HasColumnType("real");

                    b.Property<byte>("TrackWetness")
                        .HasColumnType("smallint");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("TrackId");

                    b.HasIndex("UserId", "CarId", "TrackId");

                    b.ToTable("UploadedLaps", "iracing");
                });

            modelBuilder.Entity("ApexRacers.Core.Models.Week", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DemoWeatherSummaryJson")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RaceWeekIndex")
                        .HasColumnType("integer");

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("TrackId")
                        .HasColumnType("integer");

                    b.Property<int>("WeatherProvenance")
                        .HasColumnType("integer");

                    b.Property<string>("WeatherSummaryJson")
                        .HasColumnType("text")
                        .HasColumnName("RealWeatherSummaryJson");

                    b.HasKey("Id");

                    b.HasIndex("TrackId");

                    b.HasIndex("SeasonId", "RaceWeekIndex")
                        .IsUnique();

                    b.ToTable("Weeks", "iracing");
                });

            modelBuilder.Entity("ApexRacers.Data.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<long?>("IRacingCustomerId")
                        .HasColumnType("bigint")
                        .HasColumnName("ClaimedIRacingCustomerId");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("ThemePreference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("IRacingCustomerId")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_IRacingCustomerId")
                        .HasFilter("\"ClaimedIRacingCustomerId\" IS NOT NULL");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("Users", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("Roles", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserRoles", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", "identity");
                });

            modelBuilder.Entity("ApexRacers.Core.Models.CarClassCar", b =>
                {
                    b.HasOne("ApexRacers.Core.Models.CarClass", "CarClass")
                        .WithMany("CarClassCars")
                        .HasForeignKey("CarClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApexRacers.Core.Models.Car", "Car")
                        .WithMany("CarClassCars")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("CarClass");
                });

            modelBuilder.Entity("ApexRacers.Core.Models.CarPercentileResult", b =>
                {
                    b.HasOne("ApexRacers.Core.Models.Car", "Car")
                        .WithMany("CarPercentileResults")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApexRacers.Core.Models.Series", null)
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApexRacers.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApexRacers.Core.Models.Week", "Week")
                        .WithMany("CarPercentileResults")
                        .HasForeignKey("WeekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Week");
                });

            modelBuilder.Entity("ApexRacers.Core.Models.DriverAuthorizationGrant", b =>
                {
                    b.HasOne("ApexRacers.Core.Models.DriverProofReceipt", null)
                        .WithMany()
                        .HasForeignKey("ProofReceiptId", "UserId", "CustomerId", "Provenance")
                        .HasPrincipalKey("Id", "UserId", "CustomerId", "Provenance")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ApexRacers.Core.Models.DriverCopyCleanup", b =>
                {
                    b.HasOne("ApexRacers.Core.Models.DriverAuthorizationGrant", null)
                        .WithMany()
                        .HasForeignKey("GrantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApexRacers.Core.Models.DriverLifecycleOperation", null)
                        .WithMany()
                        .HasForeignKey("OperationId", "GrantId", "OriginalLossAt")
                        .HasPrincipalKey("Id", "GrantId", "OriginalLossAt")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ApexRacers.Core.Models.DriverLifecycleOperation", b =>
                {
                    b.HasOne("ApexRacers.Core.Models.DriverAuthorizationGrant", null)
                        .WithMany()
                        .HasForeignKey("GrantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ApexRacers.Core.Models.DriverProofReceipt", b =>
                {
                    b.HasOne("ApexRacers.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ApexRacers.Core.Models.DriverPublicationAdmission", b =>
                {
                    b.HasOne("ApexRacers.Core.Models.DriverAuthorizationGrant", null)
                        .WithMany()
                        .HasForeignKey("GrantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ApexRacers.Core.Models.DriverTrackedCopy", b =>
                {
                    b.HasOne("ApexRacers.Core.Models.DriverAuthorizationGrant", null)
                        .WithMany()
                        .HasForeignKey("GrantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ApexRacers.Core.Models.KnownDevice", b =>
                {
                    b.HasOne("ApexRacers.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApexRacers.Core.Models.RefreshToken", b =>
                {
                    b.HasOne("ApexRacers.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApexRacers.Core.Models.Rival", b =>
                {
                    b.HasOne("ApexRacers.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApexRacers.Core.Models.Season", b =>
                {
                    b.HasOne("ApexRacers.Core.Models.Series", "Series")
                        .WithMany("Seasons")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Series");
                });

            modelBuilder.Entity("ApexRacers.Core.Models.SeasonCar", b =>
                {
                    b.HasOne("ApexRacers.Core.Models.Car", "Car")
                        .WithMany("SeasonCars")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApexRacers.Core.Models.Season", "Season")
                        .WithMany("SeasonCars")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("ApexRacers.Core.Models.SeasonCarClass", b =>
                {
                    b.HasOne("ApexRacers.Core.Models.CarClass", "CarClass")
                        .WithMany("SeasonCarClasses")
                        .HasForeignKey("CarClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApexRacers.Core.Models.Season", "Season")
                        .WithMany("SeasonCarClasses")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarClass");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("ApexRacers.Core.Models.SignInAccountFailure", b =>
                {
                    b.HasOne("ApexRacers.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApexRacers.Core.Models.SignInAddressFailure", b =>
                {
                    b.HasOne("ApexRacers.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApexRacers.Core.Models.Subsession", b =>
                {
                    b.HasOne("ApexRacers.Core.Models.Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApexRacers.Core.Models.Track", "Track")
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApexRacers.Core.Models.Week", "Week")
                        .WithMany("Subsessions")
                        .HasForeignKey("WeekId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Season");

                    b.Navigation("Track");

                    b.Navigation("Week");
                });

            modelBuilder.Entity("ApexRacers.Core.Models.SubsessionResult", b =>
                {
                    b.HasOne("ApexRacers.Core.Models.CarClass", "CarClass")
                        .WithMany()
                        .HasForeignKey("CarClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApexRacers.Core.Models.Car", "Car")
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApexRacers.Core.Models.Subsession", "Subsession")
                        .WithMany("Results")
                        .HasForeignKey("Provenance", "SubsessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("CarClass");

                    b.Navigation("Subsession");
                });

            modelBuilder.Entity("ApexRacers.Core.Models.UploadedLap", b =>
                {
                    b.HasOne("ApexRacers.Core.Models.Car", "Car")
                        .WithMany("UploadedLaps")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApexRacers.Core.Models.Track", "Track")
                        .WithMany("UploadedLaps")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApexRacers.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("ApexRacers.Core.Models.Week", b =>
                {
                    b.HasOne("ApexRacers.Core.Models.Season", "Season")
                        .WithMany("Weeks")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApexRacers.Core.Models.Track", "Track")
                        .WithMany("Weeks")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Season");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("ApexRacers.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("ApexRacers.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApexRacers.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("ApexRacers.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApexRacers.Core.Models.Car", b =>
                {
                    b.Navigation("CarClassCars");

                    b.Navigation("CarPercentileResults");

                    b.Navigation("SeasonCars");

                    b.Navigation("UploadedLaps");
                });

            modelBuilder.Entity("ApexRacers.Core.Models.CarClass", b =>
                {
                    b.Navigation("CarClassCars");

                    b.Navigation("SeasonCarClasses");
                });

            modelBuilder.Entity("ApexRacers.Core.Models.Season", b =>
                {
                    b.Navigation("SeasonCarClasses");

                    b.Navigation("SeasonCars");

                    b.Navigation("Weeks");
                });

            modelBuilder.Entity("ApexRacers.Core.Models.Series", b =>
                {
                    b.Navigation("Seasons");
                });

            modelBuilder.Entity("ApexRacers.Core.Models.Subsession", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("ApexRacers.Core.Models.Track", b =>
                {
                    b.Navigation("UploadedLaps");

                    b.Navigation("Weeks");
                });

            modelBuilder.Entity("ApexRacers.Core.Models.Week", b =>
                {
                    b.Navigation("CarPercentileResults");

                    b.Navigation("Subsessions");
                });
#pragma warning restore 612, 618
        }
    }
}
