// <auto-generated />
using System;
using ApexRacers.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ApexRacers.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260507161956_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ApexRacers.Core.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("ApexRacers.Core.Models.CarPercentileResult", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("CarId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("ComputedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("PercentileRank")
                        .HasColumnType("double precision");

                    b.Property<int>("SampleSize")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("WeekId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("UserId");

                    b.HasIndex("WeekId");

                    b.ToTable("CarPercentileResults");
                });

            modelBuilder.Entity("ApexRacers.Core.Models.LapTimeEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("CarId")
                        .HasColumnType("integer");

                    b.Property<long>("DriverCustomerId")
                        .HasColumnType("bigint");

                    b.Property<double>("LapTimeSeconds")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WeekId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WeekId");

                    b.HasIndex("CarId", "WeekId");

                    b.HasIndex("DriverCustomerId", "WeekId");

                    b.ToTable("LapTimeEntries");
                });

            modelBuilder.Entity("ApexRacers.Core.Models.Series", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CurrentSeason")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Series");
                });

            modelBuilder.Entity("ApexRacers.Core.Models.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("IRacingCustomerId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IRacingCustomerId")
                        .IsUnique();

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("ApexRacers.Core.Models.Week", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CarClass")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SeriesId")
                        .HasColumnType("integer");

                    b.Property<string>("TrackName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("WeekNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SeriesId");

                    b.ToTable("Weeks");
                });

            modelBuilder.Entity("ApexRacers.Core.Models.CarPercentileResult", b =>
                {
                    b.HasOne("ApexRacers.Core.Models.Car", "Car")
                        .WithMany("CarPercentileResults")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApexRacers.Core.Models.UserProfile", "User")
                        .WithMany("CarPercentileResults")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApexRacers.Core.Models.Week", "Week")
                        .WithMany("CarPercentileResults")
                        .HasForeignKey("WeekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("User");

                    b.Navigation("Week");
                });

            modelBuilder.Entity("ApexRacers.Core.Models.LapTimeEntry", b =>
                {
                    b.HasOne("ApexRacers.Core.Models.Car", "Car")
                        .WithMany("LapTimeEntries")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApexRacers.Core.Models.Week", "Week")
                        .WithMany("LapTimeEntries")
                        .HasForeignKey("WeekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Week");
                });

            modelBuilder.Entity("ApexRacers.Core.Models.Week", b =>
                {
                    b.HasOne("ApexRacers.Core.Models.Series", "Series")
                        .WithMany("Weeks")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Series");
                });

            modelBuilder.Entity("ApexRacers.Core.Models.Car", b =>
                {
                    b.Navigation("CarPercentileResults");

                    b.Navigation("LapTimeEntries");
                });

            modelBuilder.Entity("ApexRacers.Core.Models.Series", b =>
                {
                    b.Navigation("Weeks");
                });

            modelBuilder.Entity("ApexRacers.Core.Models.UserProfile", b =>
                {
                    b.Navigation("CarPercentileResults");
                });

            modelBuilder.Entity("ApexRacers.Core.Models.Week", b =>
                {
                    b.Navigation("CarPercentileResults");

                    b.Navigation("LapTimeEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
