// <auto-generated />
using System;
using ApexRacers.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ApexRacers.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ApexRacers.Core.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NameAbbreviated")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("ApexRacers.Core.Models.CarPercentileResult", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("CarId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("ComputedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("PercentileRank")
                        .HasColumnType("double precision");

                    b.Property<int>("SampleSize")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("WeekId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("UserId");

                    b.HasIndex("WeekId");

                    b.ToTable("CarPercentileResults");
                });

            modelBuilder.Entity("ApexRacers.Core.Models.LapTimeEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<float?>("AirTempCelsius")
                        .HasColumnType("real");

                    b.Property<int>("CarId")
                        .HasColumnType("integer");

                    b.Property<long>("DriverCustomerId")
                        .HasColumnType("bigint");

                    b.Property<double>("LapTimeSeconds")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float?>("TrackTempCelsius")
                        .HasColumnType("real");

                    b.Property<byte?>("TrackWetness")
                        .HasColumnType("smallint");

                    b.Property<int>("WeekId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WeekId");

                    b.HasIndex("CarId", "WeekId");

                    b.HasIndex("DriverCustomerId", "WeekId");

                    b.ToTable("LapTimeEntries");
                });

            modelBuilder.Entity("ApexRacers.Core.Models.PersonalLap", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<float>("AirTempCelsius")
                        .HasColumnType("real");

                    b.Property<int>("CarId")
                        .HasColumnType("integer");

                    b.Property<string>("ConfigName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("IracingTrackId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsValidLap")
                        .HasColumnType("boolean");

                    b.Property<double>("LapTimeSeconds")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TrackName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<float>("TrackTempCelsius")
                        .HasColumnType("real");

                    b.Property<byte>("TrackWetness")
                        .HasColumnType("smallint");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("UserId", "CarId", "IracingTrackId");

                    b.ToTable("PersonalLaps");
                });

            modelBuilder.Entity("ApexRacers.Core.Models.Season", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<int>("Quarter")
                        .HasColumnType("integer");

                    b.Property<int>("SeriesId")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SeriesId", "Year", "Quarter")
                        .IsUnique();

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("ApexRacers.Core.Models.SeasonCar", b =>
                {
                    b.Property<int>("SeasonId")
                        .HasColumnType("integer");

                    b.Property<int>("CarId")
                        .HasColumnType("integer");

                    b.HasKey("SeasonId", "CarId");

                    b.HasIndex("CarId");

                    b.ToTable("SeasonCars");
                });

            modelBuilder.Entity("ApexRacers.Core.Models.Series", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Series");
                });

            modelBuilder.Entity("ApexRacers.Core.Models.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("IRacingCustomerId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IRacingCustomerId")
                        .IsUnique();

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("ApexRacers.Core.Models.Week", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConfigName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("IracingTrackId")
                        .HasColumnType("integer");

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("TrackName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("WeekNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId", "WeekNumber")
                        .IsUnique();

                    b.ToTable("Weeks");
                });

            modelBuilder.Entity("ApexRacers.Core.Models.CarPercentileResult", b =>
                {
                    b.HasOne("ApexRacers.Core.Models.Car", "Car")
                        .WithMany("CarPercentileResults")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApexRacers.Core.Models.UserProfile", "User")
                        .WithMany("CarPercentileResults")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApexRacers.Core.Models.Week", "Week")
                        .WithMany("CarPercentileResults")
                        .HasForeignKey("WeekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("User");

                    b.Navigation("Week");
                });

            modelBuilder.Entity("ApexRacers.Core.Models.LapTimeEntry", b =>
                {
                    b.HasOne("ApexRacers.Core.Models.Car", "Car")
                        .WithMany("LapTimeEntries")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApexRacers.Core.Models.Week", "Week")
                        .WithMany("LapTimeEntries")
                        .HasForeignKey("WeekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Week");
                });

            modelBuilder.Entity("ApexRacers.Core.Models.PersonalLap", b =>
                {
                    b.HasOne("ApexRacers.Core.Models.Car", "Car")
                        .WithMany("PersonalLaps")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApexRacers.Core.Models.UserProfile", "User")
                        .WithMany("PersonalLaps")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ApexRacers.Core.Models.Season", b =>
                {
                    b.HasOne("ApexRacers.Core.Models.Series", "Series")
                        .WithMany("Seasons")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Series");
                });

            modelBuilder.Entity("ApexRacers.Core.Models.SeasonCar", b =>
                {
                    b.HasOne("ApexRacers.Core.Models.Car", "Car")
                        .WithMany("SeasonCars")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApexRacers.Core.Models.Season", "Season")
                        .WithMany("SeasonCars")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("ApexRacers.Core.Models.Week", b =>
                {
                    b.HasOne("ApexRacers.Core.Models.Season", "Season")
                        .WithMany("Weeks")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");
                });

            modelBuilder.Entity("ApexRacers.Core.Models.Car", b =>
                {
                    b.Navigation("CarPercentileResults");

                    b.Navigation("LapTimeEntries");

                    b.Navigation("PersonalLaps");

                    b.Navigation("SeasonCars");
                });

            modelBuilder.Entity("ApexRacers.Core.Models.Season", b =>
                {
                    b.Navigation("SeasonCars");

                    b.Navigation("Weeks");
                });

            modelBuilder.Entity("ApexRacers.Core.Models.Series", b =>
                {
                    b.Navigation("Seasons");
                });

            modelBuilder.Entity("ApexRacers.Core.Models.UserProfile", b =>
                {
                    b.Navigation("CarPercentileResults");

                    b.Navigation("PersonalLaps");
                });

            modelBuilder.Entity("ApexRacers.Core.Models.Week", b =>
                {
                    b.Navigation("CarPercentileResults");

                    b.Navigation("LapTimeEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
