/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-tertiary-container': '#746100',
        'secondary': '#a6e6ff',
        'on-secondary-fixed-variant': '#004e60',
        'surface-bright': '#3a393a',
        'tertiary': '#fffaf8',
        'on-surface': '#e5e2e3',
        'secondary-fixed': '#b7eaff',
        'error-container': '#93000a',
        'on-tertiary': '#3a3000',
        'on-primary-fixed': '#00210c',
        'tertiary-fixed-dim': '#e9c400',
        'inverse-surface': '#e5e2e3',
        'surface-container-high': '#2a2a2b',
        'primary-fixed': '#60ff99',
        'on-secondary-fixed': '#001f28',
        'on-surface-variant': '#b9cbb9',
        'primary-fixed-dim': '#00e479',
        'outline-variant': '#3b4b3d',
        'on-secondary-container': '#00566b',
        'on-primary-fixed-variant': '#005228',
        'on-primary': '#003919',
        'surface-container-low': '#1c1b1c',
        'on-primary-container': '#007139',
        'on-secondary': '#003543',
        'on-error-container': '#ffdad6',
        'error': '#ffb4ab',
        'surface-dim': '#131314',
        'on-error': '#690005',
        'surface-tint': '#00e479',
        'outline': '#849585',
        'surface-container': '#201f20',
        'surface-container-highest': '#353436',
        'tertiary-container': '#ffdd4f',
        'primary-container': '#00ff88',
        'surface-variant': '#353436',
        'on-tertiary-fixed-variant': '#544600',
        'inverse-on-surface': '#313031',
        'surface': '#131314',
        'secondary-container': '#14d1ff',
        'inverse-primary': '#006d37',
        'background': '#131314',
        'surface-container-lowest': '#0e0e0f',
        'primary': '#f1ffef',
        'on-tertiary-fixed': '#221b00',
        'tertiary-fixed': '#ffe16d',
        'secondary-fixed-dim': '#4cd6ff',
        'on-background': '#e5e2e3',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        margin: '24px',
        unit: '4px',
        gutter: '16px',
        'container-max': '1440px',
      },
      fontFamily: {
        'label-caps': ['Inter'],
        'headline-sm': ['Sora'],
        'headline-md': ['Sora'],
        'body-lg': ['Inter'],
        'display-lg': ['Sora'],
        'data-md': ['JetBrains Mono'],
        'data-lg': ['JetBrains Mono'],
        'body-sm': ['Inter'],
      },
      fontSize: {
        'label-caps': ['11px', { lineHeight: '1', letterSpacing: '0.1em', fontWeight: '700' }],
        'headline-sm': ['18px', { lineHeight: '1.4', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.04em', fontWeight: '800' }],
        'data-md': ['14px', { lineHeight: '1', fontWeight: '500' }],
        'data-lg': ['20px', { lineHeight: '1', fontWeight: '700' }],
        'body-sm': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
};
